/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as OMneRouteImport } from './routes/o-mne'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as SluzbyRouteImport } from './routes/sluzby'
import { Route as ApiPingRouteImport } from './routes/api.ping'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const OMneRoute = OMneRouteImport.update({
  id: '/o-mne',
  path: '/o-mne',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyRoute = SluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-mne': typeof OMneRoute
  '/portfolio': typeof PortfolioRoute
  '/reference': typeof ReferenceRoute
  '/sluzby': typeof SluzbyRoute
  '/api/ping': typeof ApiPingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-mne': typeof OMneRoute
  '/portfolio': typeof PortfolioRoute
  '/reference': typeof ReferenceRoute
  '/sluzby': typeof SluzbyRoute
  '/api/ping': typeof ApiPingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-mne': typeof OMneRoute
  '/portfolio': typeof PortfolioRoute
  '/reference': typeof ReferenceRoute
  '/sluzby': typeof SluzbyRoute
  '/api/ping': typeof ApiPingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/o-mne'
    | '/portfolio'
    | '/reference'
    | '/sluzby'
    | '/api/ping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/o-mne'
    | '/portfolio'
    | '/reference'
    | '/sluzby'
    | '/api/ping'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/o-mne'
    | '/portfolio'
    | '/reference'
    | '/sluzby'
    | '/api/ping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  OMneRoute: typeof OMneRoute
  PortfolioRoute: typeof PortfolioRoute
  ReferenceRoute: typeof ReferenceRoute
  SluzbyRoute: typeof SluzbyRoute
  ApiPingRoute: typeof ApiPingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-mne': {
      id: '/o-mne'
      path: '/o-mne'
      fullPath: '/o-mne'
      preLoaderRoute: typeof OMneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby': {
      id: '/sluzby'
      path: '/sluzby'
      fullPath: '/sluzby'
      preLoaderRoute: typeof SluzbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  OMneRoute: OMneRoute,
  PortfolioRoute: PortfolioRoute,
  ReferenceRoute: ReferenceRoute,
  SluzbyRoute: SluzbyRoute,
  ApiPingRoute: ApiPingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
